### PR TITLE
Adds portletNamespace property to Router

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
cc @brunobasto

**Comment by eduardolundgren** [comment]
Hi @julien, we can't add Liferay specific properties here since Metal doesn't know about Liferay existence. Discuss with @jbalsas and @brunobasto an alternative solution. Thanks.

**Comment by jbalsas** [comment]
Hey @julien, in portal, if this is needed, you should extend or augment `PortletBase` somehow.

**Comment by julien** [comment]
@eduardolundgren @jbalsas ok thanks

**Comment by brunobasto** [comment]
Hey guys, this was just a misunderstanding. This commit was supposed to go to somewhere else. Thanks.

**Pull request closed without merging**
