### PR TITLE
Adds 'query' object to activeState object

### PR DESCRIPTION
**Pull request by bryceosterhaus**
@jbalsas, @eduardolundgren 

Hey, wanted to send a PR for this and see what you think. One thing we needed in Faro was the ability to extract the query params for a route. Let me know if this makes sense to you or if I should add anything else. Thanks

### CODE REVIEW

**Comment by eduardolundgren** [comment]
LGTM. Maybe rename to `.query` like express?

**Comment by bryceosterhaus** [comment]
@eduardolundgren updated it to be `query`.

**Comment by bryceosterhaus** [comment]
@Robert-Frampton

**Comment by eduardolundgren** [comment]
LGTM. @Robert-Frampton could you merge and release a version? Thanks.

**Pull request merged**
